module.exports = ErrCode = {
    UserNotLogin:'用户未登陆',
    SessionExpries: 'Session过期',
    UserNameRepeated:'用户名重复',
    UserNameInvalid:'非法用户名',
    Success: '调用成功',
    DatabaseError : '数据库调用失败',
    ParametersError : '参数无效',
    BallgameExpriesed : '比赛过期',
    CannotJoinGameRepeat : '不能重复加入同一个房间',
    GameRoomScoreLimit : '竞猜房间积分达到上限',
    CreateRoomLimit : '创建房间数量达到上限',
    NoRoom : '没有创建房间',
    RoomScoreNotEnought : '房间积分不足',
    AllocScoreFail : '分配积分失败',
    CreateRoomTableFail : '创建比赛桌失败',
};